server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://192.168.2.5:3337/xiaomi?useSSL=false
    username: root
    password: 123456

  redis:
    host: 192.168.2.8
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms

  rabbitmq:
    host: 192.168.2.5
    port: 5672
    username: moximoxi
    password: moximoxi
    connection-timeout: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.mall.xiaomi: DEBUG  # 替换为您项目的具体包名
